### ISSUE TITLE
Kidaroo voice taking forever to load its not working

### ISSUE THREAD

**Issue by iLOVEP0TAT0** [Wrapper-Offline/Wrapper-Offline-Public#13]

**Comment by imageny** [comment]
That's very common. Try looking for lame.exe in Task Manager and end the process. Otherwise, try restarting Wrapper entirely and/or rebooting your computer. If all else fails, you can make it so it takes in VFProxy from Seamus's host of the software through the settings. However do keep in mind that the server being used goes down every night at 11:00PM CST/12:00AM EST/04:00 UTC, so you also have the option of making it so that it takes in the requests through the Cepstral API, but do keep in mind you won't have the Kidaroo voice if you choose to toggle the Cepstral API instead of VFProxy.

**Comment by iLOVEP0TAT0** [comment]
> That's very common. Try looking for lame.exe in Task Manager and end the process. Otherwise, try restarting Wrapper entirely and/or rebooting your computer. If all else fails, you can make it so it takes in VFProxy from Seamus's host of the software through the settings. However do keep in mind that the server being used goes down every night at 11:00PM CST/12:00AM EST/04:00 UTC, so you also have the option of making it so that it takes in the requests through the Cepstral API, but do keep in mind you won't have the Kidaroo voice if you choose to toggle the Cepstral API instead of VFProxy.

**Comment by iLOVEP0TAT0** [comment]
ok thanks its worked now!
